version: "3.9"
#serviços
services:
  #Banco de dados mongodb
  mongodb:
    image: mongo:4.4.6
    container_name: "meu-mongo"
    networks:
      - compose-bridge
  #Aplicação de api    
  app:
    image: node:16
    container_name: "minha-api"
    networks:
      - compose-bridge
    ports:
      - 3333:3333
    depends_on:
      - mongodb
#configuração de redes
networks:
  compose-bridge:
    driver: bridge